dist: trusty
sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: score-keeper-be
  on:
    repo:  akrk-dev/score-keeper-be 
  on:
    branch: master